name: main

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download
        id: dload
        run: |
          NAME=9600.16384.WINBLUE_RTM.130821-1623_X64FRE_SERVER_SOLUTION_ZH-CN-IRM_SSSO_X64FRE_ZH-CN_DV5.ISO
          TAG=2012r2
          
          wget -q https://download.microsoft.com/download/8/1/6/816441D4-3F4E-412C-847A-2463146FAF25/9600.16384.WINBLUE_RTM.130821-1623_X64FRE_SERVER_SOLUTION_ZH-CN-IRM_SSSO_X64FRE_ZH-CN_DV5.ISO
          
          if [[ -v GITHUB_WORKFLOW ]]; then
            echo "RELEASE_NAME=${NAME}" >> $GITHUB_OUTPUT
            echo "RELEASE_TAG=${TAG}" >> $GITHUB_OUTPUT
          fi

      - name: upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.dload.outputs.RELEASE_NAME }}
          path: ${{ steps.dload.outputs.RELEASE_NAME }}
