name: main

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download
        id: dload
        run: |
          NAME=exa.lnx.a_665.apk
          TAG=24.04
          
          wget -q https://f-droid.org/repo/exa.lnx.a_665.apk
          
          if [[ -v GITHUB_WORKFLOW ]]; then
            echo "RELEASE_NAME=${NAME}" >> $GITHUB_OUTPUT
            echo "RELEASE_TAG=${TAG}" >> $GITHUB_OUTPUT
          fi

      - name: upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.dload.outputs.RELEASE_NAME }}
          path: ${{ steps.dload.outputs.RELEASE_NAME }}
