name: main

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download
        id: dload
        run: |
          NAME=Windows_Server_2008_R2_x64.iso
          TAG=2008
          
          wget -q https://archive.org/download/Windows_Server_2008_R2_x64.iso_reupload/Windows_Server_2008_R2_x64.iso
          
          if [[ -v GITHUB_WORKFLOW ]]; then
            echo "RELEASE_NAME=${NAME}" >> $GITHUB_OUTPUT
            echo "RELEASE_TAG=${TAG}" >> $GITHUB_OUTPUT
          fi

      - name: upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.dload.outputs.RELEASE_NAME }}
          path: ${{ steps.dload.outputs.RELEASE_NAME }}
