name: main

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download
        id: dload
        run: |
          NAME=quarkos-24.04-x64.r2.iso
          TAG=24.04
          
          wget -q https://downloads.sourceforge.net/project/quark-os/stable/1-plasma-live-media/quarkos-24.04-x64.r2.iso?ts=gAAAAABoBKDAhTAydqfS-UvCIrHNDmUYz5JxdbA_eSH-3FUe-tyZcMwfZQ8WAoH4iB6_abm_bpUBDtysnkCXZWZLvbOUPfg4lA%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fquark-os%2Ffiles%2Fstable%2F1-plasma-live-media%2Fquarkos-24.04-x64.r2.iso%2Fdownload
          
          if [[ -v GITHUB_WORKFLOW ]]; then
            echo "RELEASE_NAME=${NAME}" >> $GITHUB_OUTPUT
            echo "RELEASE_TAG=${TAG}" >> $GITHUB_OUTPUT
          fi

      - name: upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.dload.outputs.RELEASE_NAME }}
          path: ${{ steps.dload.outputs.RELEASE_NAME }}
