name: main

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download
        id: dload
        run: |
          NAME="tiny10 x64 23h2.iso"
          TAG=tiny10-23h2
          
          wget -q https://archive.org/download/tiny-10-23-h2/tiny10%20x64%2023h2.iso
          
          if [[ -v GITHUB_WORKFLOW ]]; then
            echo "RELEASE_NAME=${NAME}" >> $GITHUB_OUTPUT
            echo "RELEASE_TAG=${TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.dload.outputs.RELEASE_NAME }}"
          path: "${{ steps.dload.outputs.RELEASE_NAME }}"

      #- name: Publish release
       # uses: ncipollo/release-action@v1
        #with:
         # allowUpdates: true
          #tag: ${{ steps.dload.outputs.RELEASE_TAG }}
          #name: ${{ steps.dload.outputs.RELEASE_NAME }}
          #artifacts: "${{ steps.dload.outputs.RELEASE_NAME }}"
          #body: |
          #  This is ${{ steps.build.outputs.RELEASE_NAME }}.
          #token: ${{ secrets.GITHUB_TOKEN }}
         
